# Spring Configuration
spring:
  profiles:
    active: dev
  application:
    name: FMS

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  data:
    redis:
      host: localhost
      port: 6379
      password:  # leave empty if no password
      timeout: 2000
      database: 0
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
      cache-null-values: false
      use-key-prefix: true
      key-prefix: fms

  datasource:
    url: jdbc:postgresql://localhost:5432/dummy_fms
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect

# Application Configuration
server:
  port: 8000
  servlet:
    context-path: /fms

# Logging configuration
logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  log-dir: logs/fms


